import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
	compile,
	type JSONSchema,
	type Options,
} from "json-schema-to-typescript";

// Configuration
const bannerComment =
	"/* eslint-disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,\n* and run `pnpm run updateSchema` to regenerate this file.\n*/";
const style: Options["style"] = {
	bracketSpacing: false,
	printWidth: 120,
	semi: true,
	singleQuote: false,
	tabWidth: 4,
	trailingComma: "none",
	useTabs: false,
};

async function main() {
	process.loadEnvFile(".env");

	const baseUrl = process.env.DEV_URL_BASE;
	if (!baseUrl?.length) {
		throw new Error("`DEV_URL_BASE` not set in .env.");
	}

	const schemaUrl = `${baseUrl}/schema.json`;

	const schemaResponse = await fetch(schemaUrl);
	if (!schemaResponse.ok) {
		throw new Error(
			`Unable to fetch schema. (status code: ${schemaResponse.status})`,
		);
	}

	const schema: JSONSchema = await schemaResponse.json();

	const tsType = await compile(schema, "ProtoRegistry", {
		bannerComment,
		style,
	});

	await writeFile(resolve("src", "types", "protoRegistry.ts"), tsType);
}

main().catch(console.error);
